Repository gtk-rs/gtk-rs, pull requests merged in 2020-11, with the labels that each got.

#135 inet_socket_address: Add std::net::SocketAddr conversions
  gio/src/inet_socket_address.rs
  gio/src/lib.rs
Labels: glib

#35 Allow log_domain to be null.
  glib/src/bridged_logging.rs
  glib/src/log.rs
  glib/tests/log.rs
Labels: bug, glib

#134 Remove completely outdated changelogs
  atk/CHANGELOG.md
  gtk/CHANGELOG.md
Labels: documentation

#27 Make virtual methods take wrapper of type, not parent
  examples/src/bin/basic_subclass.rs
  examples/src/bin/listbox_model.rs
  gio/src/read_input_stream.rs
  gio/src/subclass/application.rs
  gio/src/subclass/input_stream.rs
  gio/src/subclass/io_stream.rs
  gio/src/subclass/output_stream.rs
  gio/src/subclass/seekable.rs
  gio/src/write_output_stream.rs
  glib/src/object.rs
  glib/src/subclass/mod.rs
  glib/src/subclass/object.rs
  glib/src/subclass/simple.rs
  glib/src/subclass/types.rs
  glib/src/wrapper.rs
  gtk/src/subclass/application.rs
  gtk/src/subclass/cell_renderer.rs
  gtk/src/subclass/cell_renderer_accel.rs
  gtk/src/subclass/cell_renderer_text.rs
  gtk/src/subclass/cell_renderer_toggle.rs
  gtk/src/subclass/container.rs
  gtk/src/subclass/dialog.rs
  gtk/src/subclass/icon_view.rs
  gtk/src/subclass/list_box.rs
  gtk/src/subclass/list_box_row.rs
  gtk/src/subclass/plug.rs
  gtk/src/subclass/socket.rs
  gtk/src/subclass/widget.rs
  gtk/src/subclass/window.rs
Labels: glib

#36 CI: add a docs job
  .github/workflows/docs.yml
Labels: ci

#20 CI: add a regen check job
  .github/workflows/CI.yml
Labels: ci
